app = "epicshowdown-backend"
primary_region = "sin"  # Singapore region

# ตั้ง ENV สำหรับ ASP.NET Core
[env]
  DOTNET_ENVIRONMENT = "Dev"
  ASPNETCORE_ENVIRONMENT = "Dev"
  ASPNETCORE_URLS = "http://*:8080"
  PORT = "8080"

# สัญญาณปิดแอปที่ fly จะใช้
kill_signal = "SIGINT"
kill_timeout = 5

# กำหนด service ว่าเปิดพอร์ต 8080 ภายใน
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  # เปิดพอร์ต HTTP
  [[services.ports]]
    handlers = ["http"]
    port = 80

  # เปิดพอร์ต HTTPS (ต้องเซ็ต TLS cert ที่ fly.io ด้วย)
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  # เช็คลูกข่ายก่อนรับ traffic
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    timeout = "2s"
    port = 8080