# docker compose -p epic_showdown \
#   -f Docker/docker-compose.yml \
#   up -d --build

version: '3.8'

services:
  db:
    image: bitnami/postgresql:15
    container_name: epic_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: epicshowdown
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: epic_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: epic_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin    # เปลี่ยนตามต้องการ
      MINIO_ROOT_PASSWORD: minioadmin # เปลี่ยนตามต้องการ
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  redis_data:
  minio_data: